winereviews/reviews/urls.py
from django.conf.urls import url
from . import views


app_name = 'reviews'

urlpatterns = [
    # ex: /
    url('^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url('^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url('^wine$', views.wine_list, name='wine_list'),
    # ex: /wine/5/
    url('^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url('^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /review/user - get reviews for the logged user
    url('^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    url('^review/user/$', views.user_review_list, name='user_review_list'),
]

winereviews/winereviews/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'winereviews'

urlpatterns = [
    path('reviews/', include(('reviews.urls', app_name), namespace='reviews')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/', include(('django.contrib.auth.urls', app_name), namespace='auth')),
]

winereviews/reviews/models.py
from django.db import models
import numpy as np


# Create your models here.
class Wine(models.Model):
    name = models.CharField(max_length=200)

    def average_rating(self):
        all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
        return np.mean(all_ratings)

    def min_rating(self):
        all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
        return np.min(all_ratings)

    def max_rating(self):
        all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
        return np.max(all_ratings)

    def __unicode__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    wine = models.ForeignKey('Wine', on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)

    def return_rating_choices(self):
        return self.RATING_CHOICES

winereviews/reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15})
        }

winereviews/reviews/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Review, Wine
from .forms import ReviewForm
import datetime


# Create your views here.
def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:10]
    context = {'latest_review_list': latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    context = {'review': review}
    return render(request, 'reviews/review_detail.html', context)


def wine_list(request):
    wine_list = Wine.objects.order_by('-name')
    context = {'wine_list': wine_list}
    return render(request, 'reviews/wine_list.html', context)


def wine_detail(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm()
    context = {'wine': wine, 'form': form}
    return render(request, 'reviews/wine_detail.html', context)


@login_required
def add_review(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = request.user.username
        review = Review()
        review.wine = wine
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))
    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})


def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list': latest_review_list, 'username': username}
    return render(request, 'reviews/user_review_list.html', context)

winereviews/reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    <h3><a href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a></h3>
{% endblock %}

{% block content %}
    <h5>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h5>
    <p>{{ review.pub_date }}</p>
    <p>{{ review.comment }}</p>
{% endblock %}

winereviews/reviews/templates/reviews/review_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    <h3>Latest reviews</h3>
{% endblock %}

{% block content %}
{% if latest_review_list %}
    <div class="card-deck">
        {% for review in latest_review_list %}
            <div class="card text-center border-info mb-3" style="min-width: 10rem; max-width: 15rem;">
                <div class="card-header">
                    <a class="card-link" href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a>
                </div>
                <div class="card-body">
                    <p class="text-info">{{ review.comment }}</p>
                    <a class="card-link" href="{% url 'reviews:review_detail' review.id %}"><small class="text">Read more...</small></a>
                </div>
                <div class="card-footer">
                    <small class="text-muted">rated {{ review.rating }} of 5</small>
                    <br />
                    <small class="text-muted">by <a class="card-link" href="{% url 'reviews:user_review_list' review.user_name %}">{{ review.user_name }}</a></small>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>No reviews are available.</p>
{% endif %}
{% endblock %}

winereviews/reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Reviews by {{ username }}</h2>
{% endblock %}

winereviews/reviews/templates/reviews/wine_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    <h3>{{ wine.name }}</h3>
    <h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
    <h4>Recent reviews</h4>

    {% if wine.review_set.all %}
        <div class="card-deck">
            {% for review in wine.review_set.all %}
                <div class="card text-center border-info mb-3" style="min-width: 10rem; max-width: 15rem;">
                    <div class="card-body">
                        <p class="text-info">{{ review.comment }}</p>
                        <a class="card-link" href="{% url 'reviews:review_detail' review.id %}"><small class="text">Read more...</small></a>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">rated {{ review.rating }} of 5</small>
                        <br />
                        <small class="text-muted">by <a class="card-link" href="{% url 'reviews:user_review_list' review.user_name %}">{{ review.user_name }}</a></small>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No reviews for this wine yet</p>
    {% endif %}

    <h4>Add your review</h4>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form layout='inline' %}
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
{% endblock %}

winereviews/reviews/templates/reviews/wine_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    <h3>Wine list</h3>
{% endblock %}

{% block content %}
    {% if wine_list %}
        <div class="card-deck">
            {% for wine in wine_list %}
                <div class="card text-center border-info mb-3" style="min-width: 10rem; max-width: 15rem;">
                    <div class="card-header">
                        <a class="card-link" href="{% url 'reviews:wine_detail' wine.id %}">{{ wine.name }}</a>
                    </div>
                    <div class="card-body">
                        <p class="text-info">{{ wine.review_set.count }} reviews</p>
                        <p class="text-info">{{ wine.average_rating | floatformat }} average rating</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No wines are available.</p>
    {% endif %}
{% endblock %}

winereviews/templates/base.html
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap4_content %}
<div class="container">
    <nav class="navbar navbar-expand navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Winerama</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'reviews:review_list' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'reviews:wine_list' %}">Wine list</a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'reviews:user_review_list' user.username %}">Hello {{ user.username }}</a>
                    <a class="nav-item nav-link" href="{% url 'auth:logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'auth:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% block title %}(no title){% endblock %}

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>
{% endblock %}